---
title: "note2"
author: "yang"
date: "July 10, 2018"
output: html_document
---

# note

## know the function<br />
help()<br />
args()<br />

## operator<br />

### numeric<br />
plus:1+1<br />
minus:2-1<br />
multiple:2*2<br />
divide(can be float):5/3<br />
remainder:5%%3<br />
*only numeric can use numeric operator <br />

### logical<br />
AND:&(only the first one &&)<br />
OR:|(only the first one ||)<br />
Watch out: 3 < x < 7 to check if x is between 3 and 7 will not work; you'll need 3 < x & x < 7 for that.<br />
<br />

### condition<br />
if (condition1) {<br />
  expr1<br />
} else if (condition2) {<br />
  expr2<br />
} else if (condition3) {<br />
  expr3<br />
} else {<br />
  expr4<br />
}<br />

### while<br />
while (condition1) {<br />
  expr1<br />
  if (condition2) {<br />
    break<br />
  }<br />
  if (condition3) {<br />
    expr1<br />
  } else {<br />
    expr1<br />
  }<br />
  
### for<br />
primes <- c(2, 3, 5, 7, 11, 13)<br />

#### loop version 1<br />
for (p in primes) {<br />
  print(p)<br />
}<br />

#### loop version 2<br />
for (i in 1:length(primes)) {<br />
  print(primes[i])<br />
}<br />
<br />

## variable<br />
x<-2<br />
x<-string<br />

### type<br />
numerics ex:4.5<br />
integers ex:4<br />
logical ex:TRUE FALSE<br />
characters ex:"string"<br />
*if you wan to know the type, use:class()<br />
<br />

## Vectors<br />
with the combine function c()<br />

### choose<br />
if knowing the name: ["string"]<br />
choose more than one: [c("Monday","Tuesday")]<br />
if knowing the order:[1]<br />
choose more than one:[c(2,3,4)]equal to [2:4]<br />

### combine<br />
c(vector1,vector2)<br />

### naming<br />
names()<br />
ex:poker_vector <- c(140, -50, 20, -120, 240)<br />
ex:names(poker_vector) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")<br />
ex:days_vector<- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")<br />
      names(poker_vector) <-   days_vector<br />
      
### sum()<br />
add all the numbers in the vector OR count something<br />

### mean()<br />
average all the numbers in the vector<br />

### separate string and save<br />
strsplit(rquote, split = "")[[1]]<br />
<br />

## Matrix<br />

### construct a matrix<br />
matrix(1:9, byrow = TRUE, nrow = 3)<br />

### naming<br />
rownames(matrix_name) <- row_names_vector<br />
colnames(matrix_name) <- col_names_vector<br />
dimnames = list(c("A New Hope", "The Empire Strikes Back", "Return of the Jedi"),c("US", "non-US")))<br />

### sum<br />
use rowSums()or colSums()<br />

### add rows or columes<br />
use cbind()or rbind()<br />
ex:big_matrix <- cbind(matrix1, matrix2, vector1)<br />

### choose<br />
my_matrix[1:3,2:4]<br />
choose all of them:my_matrix[,]<br />

### example<br />
star_wars_matrix <- matrix(box_office, nrow = 3, byrow = TRUE)<br />
<br />

## factors<br />
2 kinds: nominal categorical variable  and  ordinal categorical variable<br />
will keep original vector<br />

### construct factor<br />
factor()<br />
factor(vector_name, order = TRUE, levels = c("Low", "Medium", "High"))<br />

### change order <br />
use levels(), have a look on original order <br />

### overlook the factor<br />
summary(),factoris better than vector<br />
<br />

## dataframe<br />

### construct<br />
data.frame()<br />

### check part of data<br />
head()<br />
tail()<br />
str()<br />

### choose<br />
colume:dataframe_name$col_name<br />
subset(dataframe_name, subset = some_condition)<br />

### order<br />
order()<br />
dataframe_name[order(dataframe_name),]<br />
<br />

## list<br />
can save anything<br />

### construct<br />
list()<br />

### naming<br />
my_list <- list(your_comp1, your_comp2)<br />
names(my_list) <- c("name1", "name2")<br />
<br />
my_list <- list(name1 = your_comp1, name2 = your_comp2)<br />

### choose<br />
list_name[[2]][1]<br />
list_name[["reviews"]]<br />
list_name$reviews<br />

### add new thing<br />
ext_list <- c(my_list, my_name = anything)<br />
<br />

### write a function<br />
my_fun <- function(arg1, arg2) {<br />
  body<br />
}<br />

### using advanced function<br />
install.packages()<br />

#### Chunk 1<br />
library(data.table)<br />
require(rjson)<br />

#### Chunk 2<br />
library("data.table")<br />
require(rjson)<br />

## dataframe calculate<br />
library(gapminder)<br />
library(dplyr)<br />

### choose and arrange<br />
gapminder %>%<br />
filter(year==1957)%>%<br />
mutate(lifeExpMonths=12*lifeExp)%>%<br />
arrange(desc(pop))<br />

### visable <br />
library(ggplot2) <br />
ggplot(gapminder_1952, aes(x = pop, y = lifeExp, color = continent,size=gdpPercap)) +<br />
  geom_point()+<br />
  geom_line()+<br />
  geom_col()+<br />
  geom_histogram(binwidth=5)<br />
  geom_boxplot()<br />
  scale_x_log10()+<br />
  facet_wrap(~ continent)+<br />
  expand_limits(y=0)<br />
  
### summarize<br />
gapminder %>% summarize(medianLifeExp=median(lifeExp),maxGdpPercap=max(gdpPercap))<br />