---
title: "week3_lab2"
author: "yang"
date: "2018年7月18日"
output: html_document
---

#prepare
```{r results=FALSE,warning=FALSE}
library(bitops)
library(httr)
library(RCurl)
library(tm)
library(NLP)
library(tmcn)
library(jiebaRD)
library(jiebaR)
library(devtools)
library(scales)
library(grid)
library(ggbiplot)
library(Matrix)
```
# INPUT DATA
#基本文字清洗
```{r }
d.corpus <- Corpus( DirSource("./DATA") )
d.corpus <- tm_map(d.corpus, removePunctuation)#刪除標點符號
d.corpus <- tm_map(d.corpus, removeNumbers)#刪除數字
d.corpus <- tm_map(d.corpus, function(word) {
  gsub("[A-Za-z0-9]", "", word)#刪除英文及空白
})
```
# 建立文本矩陣TDM
```{r}
mixseg = worker()
jieba_tokenizer = function(d){unlist( segment(d[[1]], mixseg) )}
seg = lapply(d.corpus, jieba_tokenizer)#unlist

count_token = function(d){ as.data.frame(table(d))}
tokens = lapply(seg, count_token)#轉成dataframe

n = length(seg)#字串長度
TDM = tokens[[1]]
colNames <- names(seg)
colNames <- gsub(".txt", "", colNames)#建立欄名稱
for( id in c(2:n) )
{
  TDM = merge(TDM, tokens[[id]], by="d", all = TRUE)
  names(TDM) = c('d', colNames[1:id])
}
TDM[is.na(TDM)] <- 0
```
# TF-IDF
```{r}
tf <- apply(as.matrix(TDM[,2:(n+1)]), 2, sum)#轉成矩陣

idfCal <- function(word_doc)
{ 
  log2( n / nnzero(word_doc) ) 
}#計算公式

idf <- apply(as.matrix(TDM[,2:(n+1)]), 1, idfCal)#轉成矩陣

doc.tfidf <- TDM
tempY = matrix(rep(c(as.matrix(tf)), each = length(idf)), nrow = length(idf))
tempX = matrix(rep(c(as.matrix(idf)), each = length(tf)), ncol = length(tf), byrow = TRUE)
doc.tfidf[,2:(n+1)] <- (doc.tfidf[,2:(n+1)] / tempY) * tempX

stopLine = rowSums(doc.tfidf[,2:(n+1)])
delID = which(stopLine == 0)
```
# PCA
```{r}
t = as.data.frame(t(doc.tfidf))#轉換欄列
t = t[-1,]
t = apply(t[,1:10], 2, as.numeric)
t = apply(t[,1:10], 1, as.numeric)
pcat = prcomp(t)
g <- ggbiplot(pcat, obs.scale = 1, var.scale = 1, ellipse = TRUE, circle = TRUE)
```
# Kmeans
```{r}
kmeansData = pcat$rotation[,1:2]
cl <- kmeans(kmeansData, 2)
plot(kmeansData, col = cl$cluster)
points(cl$centers, col = 1:2, pch = 8, cex = 2)
```
